Moved Markdown files to doc directory
DedSecInside/TorBot pull request #305
Opened 2023-10-09 02:56 UTC by shaswat-satyam

Issue #304 304 

### Changes Proposed
- Moved Markdown Files to a separate doc Directory
- 
- 

### Explanation of Changes

### Screenshots of new feature/change

2023-10-09 03:49 UTC, PSNAppz requested changes

2023-10-09 03:49 UTC, PSNAppz commented on docs/README.md
Don't move the README.md. It has to be in the root dir.

2023-10-09 12:14 UTC, KingAkeem requested changes
Could you remove the pull request template? It's being moved in another PR, https://github.com/DedSecInside/TorBot/pull/306.

2023-10-11 10:21 UTC, shaswat-satyam commented
Done

2023-10-11 10:37 UTC, PSNAppz requested changes
One last thing. We are referencing the `Licensing` url in `Readme`. Can you fix that also?

2023-10-11 11:00 UTC, shaswat-satyam commented
There you go!

2023-10-11 22:41 UTC, KingAkeem requested changes
Could you move the LICENSE.md back to the root directory so that it can be detected GitHub?

2023-10-12 17:17 UTC, KingAkeem approved these changes

2023-10-12 17:17 UTC, merged